#!/bin/bash

# Define Plex tag
case ${DOCKER_TAG} in
    # Default to latest
    "")
        PLEX_TAG="latest";;
    # Pull requests
    "this")
        PLEX_TAG="latest";;
    # Force develop branch to use beta tag
    "develop")
        PLEX_TAG="beta";;
    # Everything else use provided docker tag
    *)
        PLEX_TAG="${DOCKER_TAG}";;
esac

# Debug
echo "Using BRANCH: ${SOURCE_BRANCH}"
echo "Using COMMIT: ${SOURCE_COMMIT}"
echo "Using DOCKER_TAG: ${DOCKER_TAG}"
echo "Using PLEX_TAG: ${PLEX_TAG}"

# Build
docker build --pull --build-arg BRANCH=${SOURCE_BRANCH} --build-arg COMMIT=${SOURCE_COMMIT} --build-arg TAG=${PLEX_TAG} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
