#!/usr/bin/with-contenv bash

if [[ -z "${NVIDIA_VISIBLE_DEVICES}" ]]; then
	# NVIDIA Environment Variables were not set - do not check / apply patch
	echo "** Plex Transcoder will not be patched for Nvidia Hardware Decoding **"
else

	# NVIDIA Environment Variables were set - check patch exists / apply patch

  # Current Transcoder location
	FILENAME="/usr/lib/plexmediaserver/Plex Transcoder"
  # Size to distinguish between patch and Transcoder
	MAXSIZE=200000
  # Get size of file Transcoder
	FILESIZE=$(stat -c%s "$FILENAME")

	if (( FILESIZE < MAXSIZE )); then
		echo "** Plex Transcoder was already patched to enable Nvidia Hardware Decoding **"
	else
		mv /usr/lib/plexmediaserver/Plex\ Transcoder /usr/lib/plexmediaserver/Plex\ Transcoder2
		cp /etc/new-transcoder.sh /usr/lib/plexmediaserver/Plex\ Transcoder
		chmod 755 /usr/lib/plexmediaserver/Plex\ Transcoder
		chmod u+x /usr/lib/plexmediaserver/Plex\ Transcoder
		echo "** Plex Transcoder was patched to enable Nvidia Hardware Decoding **"
	fi
fi
